### ISSUE TITLE
Segfault on NVidia Optimus using X11

### ISSUE THREAD

**Issue by icefoxen** [rust-windowing/glutin#1194]
Original issue here, including platform info:  https://github.com/ggez/ggez/issues/658

Essentially, a user tries to run a ggez program and it segfaults during GL context init (silently, inconveniently).  GDB backtrace shows the segfault happening in XCB after passing through `glutin_glx_sys` and `libGLX_indirect.so`, so I would expect the next step would be to try to reproduce in pure glutin.  Any other suggestions are welcome!

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7092800 in xcb_glx_query_server_string_string_length () from /usr/lib/libxcb-glx.so.0
(gdb) backtrace
#0  0x00007ffff7092800 in xcb_glx_query_server_string_string_length () from /usr/lib/libxcb-glx.so.0
#1  0x00007ffff71256bc in ?? () from /usr/lib/libGLX_indirect.so.0
#2  0x00007ffff71232e7 in ?? () from /usr/lib/libGLX_indirect.so.0
#3  0x00007ffff711ed35 in ?? () from /usr/lib/libGLX_indirect.so.0
#4  0x00007ffff711f2ae in ?? () from /usr/lib/libGLX_indirect.so.0
#5  0x0000555555ad30dd in glutin_glx_sys::glx::Glx::QueryExtensionsString (
    self=0x5555561c8f20 <<glutin::api::glx::GLX as core::ops::deref::Deref>::deref::__stability::LAZY>, dpy=0x5555561e8000, screen=0)
    at /home/waffle/projects/ggez_optimus/target/debug/build/glutin_glx_sys-f9834f2527e4df32/out/glx_bindings.rs:553
#6  0x0000555555acc576 in glutin::api::glx::Context::new (xconn=..., pf_reqs=0x7ffffffeac50, opengl=0x7ffffffe8ee0, screen_id=0, transparent=false)
    at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.20.0/src/api/glx/mod.rs:102
#7  0x0000555555ad6878 in glutin::platform::platform::x11::Context::new (wb=..., el=0x7fffffff38c8, pf_reqs=0x7ffffffeac50, gl_attr=0x7ffffffea970)
    at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.20.0/src/platform/linux/x11.rs:98
#8  0x0000555555ae7c10 in glutin::platform::platform::Context::new_windowed (wb=..., el=0x7fffffff38c8, pf_reqs=0x7ffffffeac50, gl_attr=0x7ffffffeac98)
    at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.20.0/src/platform/linux/mod.rs:114
#9  0x0000555555ad9a51 in glutin::windowed::WindowedContext::new_windowed (wb=..., cb=..., el=0x7fffffff38c8)
    at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.20.0/src/windowed.rs:57
#10 0x00005555557723d9 in gfx_window_glutin::init_raw (window=..., context=..., events_loop=0x7fffffff38c8, color_format=..., ds_format=...)
    at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.30.0/src/lib.rs:146
#11 0x000055555564feb4 in <ggez::graphics::GlBackendSpec as ggez::graphics::BackendSpec>::init (self=0x7ffffffecae0, window_builder=..., gl_builder=...,
    events_loop=0x7fffffff38c8, color_format=..., depth_format=...) at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.0-rc.2/src/graphics/mod.rs:248
#12 0x00005555556e34df in ggez::graphics::context::GraphicsContextGeneric<ggez::graphics::GlBackendSpec>::new (filesystem=0x7fffffffbc10, events_loop=0x7fffffff38c8,
    window_setup=0x7fffffffbbb0, window_mode=..., backend=..., debug_id=...)
    at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.0-rc.2/src/graphics/context.rs:145
#13 0x000055555568a5a4 in ggez::context::Context::from_conf (conf=..., fs=...)
    at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.0-rc.2/src/context.rs:72
#14 0x000055555568b770 in ggez::context::ContextBuilder::build (self=...) at /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.0-rc.2/src/context.rs:273
#15 0x0000555555631d95 in ggez_optimus::main () at src/main.rs:4
```

For my own reference the settings used are the `ggez` 0.5.2-rc.2 release defaults defined [here](https://github.com/ggez/ggez/blob/960866e66b7f8c26e5a951cffef764679358b9a2/src/conf.rs#L55-L346) and applied [here](https://github.com/ggez/ggez/blob/960866e66b7f8c26e5a951cffef764679358b9a2/src/graphics/context.rs#L120-L151).

**Comment by ZeGentzy** [comment]
https://github.com/rust-windowing/glutin/pull/1199
