### ISSUE TITLE
"internal error: entered unreachable code"

### ISSUE THREAD

**Issue by lewisdiamond** [rust-windowing/glutin#1244]
```
$ RUST_BACKTRACE=full cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/window`
thread 'main' panicked at 'internal error: entered unreachable code', glutin/src/platform_impl/unix/x11.rs:167:17
stack backtrace:
   0:     0x564982283f4b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x564982283f4b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x564982283f4b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x564982283f4b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x564982283f4b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x564982283c26 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5649822846bd - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x56498213e325 - std::panicking::begin_panic::hb76d61b85bcb90d8
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:411
   8:     0x564981e51830 - glutin::platform_impl::platform_impl::x11::select_config::hb16936e83c7b5d9b
                               at glutin/src/platform_impl/unix/x11.rs:167
   9:     0x564981e5663f - glutin::api::glx::choose_fbconfig::h4e28c5776764a417
                               at glutin/src/api/glx/mod.rs:771
  10:     0x564981e52bb2 - glutin::api::glx::Context::new::hf197a5f3f3a12b43
                               at glutin/src/api/glx/mod.rs:115
  11:     0x564981e15be1 - glutin::platform_impl::platform_impl::x11::Context::new_first_stage::{{closure}}::heb29abf769c96683
                               at /home/ldiamond/dev/glutin/glutin/src/platform_impl/unix/x11.rs:350
  12:     0x564981e3bc16 - glutin::platform_impl::platform_impl::x11::Context::new_first_stage::h8a095093b4839ae9
                               at /home/ldiamond/dev/glutin/glutin/src/platform_impl/unix/x11.rs:395
  13:     0x564981e1684f - glutin::platform_impl::platform_impl::x11::Context::new_impl::h936cae69b6c3fe6c
                               at /home/ldiamond/dev/glutin/glutin/src/platform_impl/unix/x11.rs:485
  14:     0x564981e16532 - glutin::platform_impl::platform_impl::x11::Context::new::{{closure}}::hc3a702e8365223f5
                               at /home/ldiamond/dev/glutin/glutin/src/platform_impl/unix/x11.rs:458
  15:     0x564981e15eee - glutin::platform_impl::platform_impl::x11::Context::try_then_fallback::hb7201f4e185197ef
                               at /home/ldiamond/dev/glutin/glutin/src/platform_impl/unix/x11.rs:178
  16:     0x564981e1646f - glutin::platform_impl::platform_impl::x11::Context::new::h85db91b0e63c8588
                               at /home/ldiamond/dev/glutin/glutin/src/platform_impl/unix/x11.rs:457
  17:     0x564981e201fe - glutin::platform_impl::platform_impl::Context::new_windowed::ha0af1665e147a527
                               at /home/ldiamond/dev/glutin/glutin/src/platform_impl/unix/mod.rs:115
  18:     0x564981e0ca7a - glutin::windowed::<impl glutin::ContextBuilder<T>>::build_windowed::hb20f7897c26b9410
                               at /home/ldiamond/dev/glutin/glutin/src/windowed.rs:362
  19:     0x564981e0360f - window::main::hf4ec1f531c63283b
                               at glutin_examples/examples/window.rs:13
  20:     0x564981e1d040 - std::rt::lang_start::{{closure}}::hf8d154bc2c142ffc
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  21:     0x5649822840c3 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  22:     0x5649822840c3 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  23:     0x564982287dfa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  24:     0x564982284bcd - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  25:     0x564982284bcd - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  26:     0x564982284bcd - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  27:     0x564981e1d019 - std::rt::lang_start::h04b6a9cd6d0c77b7
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  28:     0x564981e0391a - main
  29:     0x7fe57f1d5153 - __libc_start_main
  30:     0x564981dbd19e - _start
  31:                0x0 - <unknown>

```
```
$ nvidia-smi
Sun Dec  1 14:51:51 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960     Off  | 00000000:09:00.0  On |                  N/A |
|  0%   58C    P0    31W / 128W |    844MiB /  2001MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1750      G   /usr/lib/Xorg                                345MiB |
|    0      3346      G   ...quest-channel-token=9925418972994524918   150MiB |
|    0    191259      G   ...nd/.local/share/Steam/ubuntu12_32/steam    46MiB |
|    0    191284      G   ./steamwebhelper                               1MiB |
|    0    191299      G   ...uest-channel-token=16712109246807870190   292MiB |
+-----------------------------------------------------------------------------+
```

**Comment by goddessfreya** [comment]
Can you try applying this patch:
```diff
diff --git a/glutin/src/platform_impl/unix/x11.rs b/glutin/src/platform_impl/unix/x11.rs
index 2c0b2e9..8288bcd 100644
--- a/glutin/src/platform_impl/unix/x11.rs
+++ b/glutin/src/platform_impl/unix/x11.rs
@@ -154,7 +154,7 @@ where
         Some(Ok(())) => (),
         Some(Err(Lacks::Transparency)) => warn!("Glutin could not a find fb config with an alpha mask. Transparency may be broken."),
         Some(Err(Lacks::XID)) => panic!(),
-        None => unreachable!(),
+        None => warn!("No configs were found. Period."),
     }
 
     chosen_conf_id.ok_or(())
```

**Comment by lewisdiamond** [comment]
Your patch did not apply on `master`, not sure what revision this is for. I manually modified the code and here's the error:
```
$ RUST_BACKTRACE=full cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/examples/window`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, NoAvailablePixelFormat])', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x556dd155615b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x556dd155615b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x556dd155615b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x556dd155615b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x556dd155615b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x556dd1555e36 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x556dd15568cd - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x556dd1556452 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x556dd1556336 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x556dd1571a2d - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x556dd1571b27 - core::result::unwrap_failed::hf7591c1dd9412006
                               at src/libcore/result.rs:1084
  11:     0x556dd10dc9a9 - core::result::Result<T,E>::unwrap::h5da149158add4ae0
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:852
  12:     0x556dd10d562e - window::main::hf4ec1f531c63283b
                               at glutin_examples/examples/window.rs:13
  13:     0x556dd10ef040 - std::rt::lang_start::{{closure}}::hf8d154bc2c142ffc
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  14:     0x556dd15562d3 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  15:     0x556dd15562d3 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  16:     0x556dd155a00a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  17:     0x556dd1556ddd - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  18:     0x556dd1556ddd - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  19:     0x556dd1556ddd - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  20:     0x556dd10ef019 - std::rt::lang_start::h04b6a9cd6d0c77b7
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  21:     0x556dd10d591a - main
  22:     0x7f68af8a9153 - __libc_start_main
  23:     0x556dd108f19e - _start
  24:                0x0 - <unknown>
```

**Comment by goddessfreya** [comment]
What version of glutin is this?

**Comment by lewisdiamond** [comment]
This is on `master`

**Comment by goddessfreya** [comment]
Hmm, can you figure out why there appears to be no `config_ids` passed to https://github.com/rust-windowing/glutin/blob/master/glutin/src/platform_impl/unix/x11.rs#L102 ? 

We should be checking to make sure there is at least one [here](https://github.com/rust-windowing/glutin/blob/master/glutin/src/api/glx/mod.rs#L767) so I don't know why it's reaching that unreachable.

**Comment by lewisdiamond** [comment]
The problem seems to be that https://github.com/rust-windowing/glutin/blob/master/glutin/src/platform_impl/unix/x11.rs#L125 is always null (`.is_null() == true`).

**Comment by goddessfreya** [comment]
@lewisdiamond I'm honestly not sure why that call is still there. It was moved here: https://github.com/rust-windowing/glutin/blob/7fa2a6a9b1f50158631da0d2901b8fb62aab3f82/glutin/src/platform_impl/unix/x11/utils.rs#L57 Should be safe to just delete the one in x11.rs. Could you file a PR?
