### ISSUE TITLE
Create glutin window failed with "Android's native windows is null"

### ISSUE THREAD

**Issue by lazytiger** [rust-windowing/glutin#1428]
I have tried to move window initializing code to Event::Resumed event, but that event never called. Can somebody give a working example?

```rust
    let el = EventLoop::new();
    let gel: &'static EventLoop<()> = unsafe { std::mem::transmute(&el) };
    el.run(|event, _, control_flow| {
        *control_flow = ControlFlow::Poll;
        match event {
            Event::Resumed => {
                log::info!("window resumed");
                let window_builder = WindowBuilder::new().with_title("hello");
                let context_builder = ContextBuilder::new()
                    .with_gl(GlRequest::GlThenGles {
                        opengl_version: (2, 1),
                        opengles_version: (2, 0),
                    })
                    .with_pixel_format(24, 8);
                let (window, device, mut factory, main_color, main_depth) =
                    gfx_window_glutin::init::<
                        gfx_core::format::Rgba8,
                        gfx_core::format::DepthStencil,
                        (),
                    >(window_builder, context_builder, gel)
                    .unwrap();
            }
            e => log::info!("event:{:?}", e),
        }
    });
```

Android logcat shows
```shell
07-25 18:27:26.474  1935  2319 I ActivityManager: Start proc 23474:rust.gars/u0a64 for activity rust.gars/android.app.NativeActivity
07-25 18:27:26.505 23474 23474 D houdini : [23474] Added shared library /data/app/rust.gars-2/lib/arm64/libgars.so for ClassLoader by Native Bridge.
07-25 18:27:26.509 23474 23491 I gars    : gars: Part 1: Drawing a triangle
07-25 18:27:26.511 23474 23491 I gars    : gars: event:NewEvents(Init)
07-25 18:27:26.512 23474 23491 I gars    : gars: event:MainEventsCleared
07-25 18:27:26.512 23474 23491 I gars    : gars: event:RedrawEventsCleared
07-25 18:27:26.513 23474 23491 I gars    : gars: event:NewEvents(Poll)
07-25 18:27:26.540  1935  2296 D WindowManager: calling BstHostCallManagerService onActivityDisplayed method, packageName: rust.gars, activityName: android.app.NativeActivity
07-25 18:27:26.541  1935  1966 I HCALL   : hcallOnActivityDisplayedRpc(rust.gars, android.app.NativeActivity)
07-25 18:27:26.542  1935  2296 D WindowManager: calling BstHostCallManagerService setAppConfigDbParams method, packageName: rust.gars, macrosDisabled: false, showFeedbackPopup: false, mouseCursorStyle: , nativeGamepad:false
07-25 18:27:26.542  1935  1966 I HCALL   : hcallSetAppConfigDbParamsRpc(rust.gars, 0, 0, , 0)
07-25 18:27:26.587  1935  2296 D InputMethodManagerService: packageName=rust.gars, activityName=android.app.NativeActivity
07-25 18:27:26.603  1935  1957 D ActivityManager: windowsDrawnLocked: packageName = rust.gars, name = android.app.NativeActivity, mCallingPackage = com.bluestacks.launcher
07-25 18:27:26.603  1935  1957 I ActivityManager: Displayed rust.gars/android.app.NativeActivity: +140ms


07-25 18:28:17.404  1935  1957 D ActivityManager: windowsDrawnLocked: packageName = rust.gars, name = android.app.NativeActivity, mCallingPackage = com.bluestacks.launcher
07-25 18:28:22.821  1935  1957 D ActivityManager: windowsDrawnLocked: packageName = rust.gars, name = android.app.NativeActivity, mCallingPackage = com.bluestacks.launcher
07-25 18:28:23.822  1935  1957 D ActivityManager: windowsDrawnLocked: packageName = rust.gars, name = android.app.NativeActivity, mCallingPackage = com.bluestacks.launcher
07-25 18:28:24.371  1935  1957 D ActivityManager: windowsDrawnLocked: packageName = rust.gars, name = android.app.NativeActivity, mCallingPackage = com.bluestacks.launcher
07-25 18:28:25.421  1935  1957 D ActivityManager: windowsDrawnLocked: packageName = rust.gars, name = android.app.NativeActivity, mCallingPackage = com.bluestacks.launcher
07-25 18:28:33.429  1935  1957 V WindowManager: isVisibleLw false for win : Window{41057e0 u0 rust.gars/android.app.NativeActivity}
07-25 18:28:46.609  1935  2232 D ActivityManager: TopActivityInfo, pkgName: rust.gars activityName: rust.gars/android.app.NativeActivity callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
07-25 18:28:46.688  1935  4687 D WindowManager: calling BstHostCallManagerService onActivityDisplayed method, packageName: rust.gars, activityName: android.app.NativeActivity
07-25 18:28:46.689  1935  1966 I HCALL   : hcallOnActivityDisplayedRpc(rust.gars, android.app.NativeActivity)
07-25 18:28:46.690  1935  4687 D WindowManager: calling BstHostCallManagerService setAppConfigDbParams method, packageName: rust.gars, macrosDisabled: false, showFeedbackPopup: false, mouseCursorStyle: , nativeGamepad:false
07-25 18:28:46.690  1935  1966 I HCALL   : hcallSetAppConfigDbParamsRpc(rust.gars, 0, 0, , 0)
07-25 18:28:46.691  1935  1957 D ActivityManager: windowsDrawnLocked: packageName = rust.gars, name = android.app.NativeActivity, mCallingPackage = com.bluestacks.launcher
07-25 18:28:46.692  1935  4687 D InputMethodManagerService: packageName=rust.gars, activityName=android.app.NativeActivity
```

**Comment by MarijnS95** [comment]
I've transferred this issue over to `glutin` since it's a `glutin`-specific issue.

We have recently made `glutin` compile against Android proper again, but I don't think the fruits of that have been released. Very soon though, it's likely going to happen around or after the time `winit 0.27` drops, hopefully before the decoupling though (cc @kchibisov who's making many many more improvements here).

You might want to look at the Android + glutin example: https://github.com/rust-windowing/glutin/pull/1417 - take special care to match the `glutin`, `winit` and `ndk` versions as per https://github.com/rust-windowing/winit#android.

**Comment by MarijnS95** [comment]
Also, as @maroider pointed out, you're very unlikely to get help when using older/discontinued crates; hence I pointed you to recent examples and repos which should help you on your way to use an up-to-date system!

**Comment by kchibisov** [comment]
In general the plan is to release winit, then glutin, and then decouple both.

**Comment by lazytiger** [comment]
Thanks for all the replies. By using glutin with android-example branch and ndk-glue with version 0.5, I finally got a Resumed event, but a new problem arose.
```rust
  log::info!("window resumed");
                let window_builder = WindowBuilder::new().with_title("hello");
                let context_builder = ContextBuilder::new()
                    .with_pixel_format(24, 8)
                    .with_multisampling(1)
                    .with_gl(GlRequest::Latest)
                    .with_srgb(true)
                    .with_depth_buffer(8)
                    .with_stencil_buffer(8)
                    .build_windowed(window_builder, el)
                    .unwrap()
                    .make_current()
                    .unwrap();
                log::info!("windows created");
```

```shell
07-26 11:17:24.349 12772 12814 I gars    : gars: window resumed
07-26 11:17:24.361 12772 12814 E libEGL  : validate_display:99 error 3008 (EGL_BAD_DISPLAY)
07-26 11:17:24.362 12772 12814 I AGA     : hstInit: opened /dev/bstpgaipc: fd = 50
07-26 11:17:24.362 12772 12814 I AGA     : Attempting to create new SOCKET connection pid = 12772, tid = 12814
07-26 11:17:24.362 12772 12814 I AGA     : hstInitClientPgaIpc: Attempting to get GROUP2 cid
07-26 11:17:24.365 12772 12814 I AGA     : hstInitClientPgaIpc: data mapped to 0x7399dfa07000 with size 4194304
07-26 11:17:24.365 12772 12814 I AGA     : New SOCKET connection: rust.gars (pid 12772, tid 12814)
07-26 11:17:24.365 12772 12814 W         : Process pipe failed
07-26 11:17:24.367 12772 12814 E EGL_emulation: tid 12814: eglBindAPI(1179): error 0x300c (EGL_BAD_PARAMETER)
07-26 11:17:24.369 12772 12813 I RustStdoutStderr: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', src\lib.rs:58:22
07-26 11:17:24.369 12772 12813 I RustStdoutStderr: stack backtrace:
07-26 11:17:24.371 12772 12813 I RustStdoutStderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The with_xxx functions were added one by one, but with no luck.

**Comment by lazytiger** [comment]
I've got another problem, I am not sure it's ok to post here.
```shell
07-27 12:51:09.305  5650  5692 I gars    : gfx_backend_gl::window::egl: Using default platform
07-27 12:51:09.305  5650  5692 I gars    : gfx_backend_gl::window::egl: Display vendor "Android", version (1, 4), extensions: "EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context "
07-27 12:51:09.305  5650  5692 I gars    : gfx_backend_gl::window::egl: Trying presentation
07-27 12:51:09.306  1566  1747 I ActivityTaskManager: Displayed rust.gars/android.app.NativeActivity: +237ms
07-27 12:51:09.306  1566  1727 I ViewRootImpl: dispatchDetachedFromWindow in doDie
07-27 12:51:09.307   839  1006 E BufferQueueProducer: [rust.gars/android.app.NativeActivity#0]:1259: connect: already connected (cur=1 req=1)
07-27 12:51:09.307  5650  5692 E libEGL  : eglCreateWindowSurface: native_window_api_connect (win=0x73cf7c9010) failed (0xffffffea) (already connected to another API?)
07-27 12:51:09.307  5650  5692 E libEGL  : eglCreateWindowSurfaceTmpl:738 error 3003 (EGL_BAD_ALLOC)
07-27 12:51:09.307  5650  5692 W gars    : gfx_backend_gl::window::egl: Error in create_platform_window_surface: BadAlloc
07-27 12:51:09.307  5650  5650 W InputMethodManager: startInputReason = 5
07-27 12:51:09.307  5650  5691 I RustStdoutStderr: thread '<unnamed>' panicked at 'Failed to create surface for window: UnsupportedWindowHandle', src\gfx.rs:220:26
```
